export const SET_USERNAME = 'SET_USERNAME';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const REGISTER_MAIL = 'REGISTER_MAIL';
export const REGISTER_USERNAME = 'REGISTER_USERNAME';
export const REGISTER_PASSWORD = 'REGISTER_PASSWORD';